"""add usermixin to user class

Revision ID: 4e13fd611d17
Revises: 0282f1a7ba20
Create Date: 2022-04-17 19:31:49.055490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e13fd611d17'
down_revision = '0282f1a7ba20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=150), nullable=True))
    op.drop_column('user', 'is_anonymous')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'is_authenticated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_anonymous', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
